name: outside_server
description: A server app to communicate with outside project.
version: 0.0.1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  grpc: ^3.1.0
  protobuf: ^2.1.0
  shelf: any
  shelf_static: any
  path: ^1.8.2
  web_socket_channel: ^2.2.0
  shelf_plus: ^1.5.0

dev_dependencies:
  build_runner:
  build_web_compilers: 
